### ISSUE TITLE
Inconsistent password acceptance

### ISSUE THREAD

**Issue by Emanuel-de-Jong** [katago/katago-server#114]
I tried to contribute with training for the first time, but the console directly said my username/password combination was wrong. It turned out I had a character in my password that caused the issue. The special characters I had were '@' and '#'. I suspect the config reader saw # as a comment and didn't take the characters after into account.

The problem is that the site let me make a password with the character. So I would recommend either disallowing the character when creating a password (though of course existing password will still have the problem) or fixing the bug that causes the error.

**Comment by Emanuel-de-Jong** [comment]
Most likely fixed in: https://github.com/lightvector/KataGo
With the commit: https://github.com/lightvector/KataGo/commit/a4637df32f31cacf8794987c75570ee31c5f06e5
Though I have not tested it myself.

**Comment by lightvector** [comment]
Yep, thanks for reporting!
