### ISSUE TITLE
verification mail sender issue

### ISSUE THREAD

**Issue by kcwu** [katago/katago-server#84]
When register, katago server will send an verification mail.

The problem is, the sender is filled as `noreply@mail.katagotraining.org`. Note the domain `mail.katagotraining.org` doesn't exist. My mail server thought mails from non-existing domains are spam and rejected them.

Please either set up `mail.katagotraining.org` domain, or change the sender to something like `noreply@katagotraining.org`.

**Comment by lightvector** [comment]
Thanks. I have configured Cloudflare to have an A record for `mail.katagotraining.org` and set a page rule for it handle http requests for it by redirecting to `katagotraining.org`.

Hopefully this handles the problem?

@tychota - I also did the same for `www.katagotraining.org`, which previously was unhandled, and made it redirect to `katagotraining.org`. Let me know if this seems to you like a reasonable solution.

**Comment by tychota** [comment]
@kcwu can you give us more info about your mail server. Eg the name ? Or if self made the technologie.

@lightvector i suspect that it won't be as simple. Mail use other dns kind.
- MX for mail receiving (points to a dns that points to ip through A record) 
- PTR
- TXT spf
- TXT dkim

The first one make it works. 
The last three are key on not being categorize as spam.

See https://www.rackaid.com/blog/email-dns-records/

Normally we have a mailgun or sendgrid domaine and they provide us config for those three fields
Not sure what doesn't works.

**Comment by kcwu** [comment]
It is postfix's **reject_unknown_sender_domain**

According to the [document](http://www.postfix.org/postconf.5.html#reject_unknown_sender_domain)
> Reject the request when Postfix is not final destination for the sender address, and the MAIL FROM domain has 1) no DNS MX and no DNS A record, or 2) a malformed MX record such as a record with a zero-length MX hostname

FYI, after @lightvector 's configuration, I already received the verification mail.

**Comment by tychota** [comment]
Interesting, and thanks for the document @kcwu
